version: "3.7"

services:
  rs3Server1:
    container_name: rs3Server1
    image: mongo-cluster
    environment:
      - MONGO_TYPE=replica3
      - IS_PRIMARY=true
      - REPLICA_SERVERS=replica3/200.100.1.215:50001,200.100.1.215:50002,200.100.1.215:50003
      - REPLICA_CHECKER=replica3/200.100.1
      - ADMIN_USER_ID=admin-user
      - ADMIN_USER_PASSWORD=admin-user-pw
      - MONGOS_IP=200.100.1.104
    volumes:
      - rs3Server1:/data/db
    ports:
      - 50001:27017
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2g
  rs3Server2:
    container_name: rs3Server2
    image: mongo-cluster
    environment:
      - MONGO_TYPE=replica3
    volumes:
      - rs3Server2:/data/db
    ports:
      - 50002:27017
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2g

  rs3Server3:
    container_name: rs3Server3
    image: mongo-cluster
    environment:
      - MONGO_TYPE=replica3
    volumes:
      - rs3Server3:/data/db
    ports:
      - 50003:27017
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  rs3Server1: {}
  rs3Server2: {}
  rs3Server3: {}
